### ISSUE TITLE
Add custom cloud-init script option to cloud-init settings

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui-components#104]
@andybraren we need to allow user to add his own cloud-init yaml script see https://bugzilla.redhat.com/show_bug.cgi?id=1648317 can you please design something ? User should be able to choose if he wants to use his own script and copy/paste into some text area or use already existing basic hostname/ssh-key config. He cannot use both.

**Comment by andybraren** [comment]
Here's what can be built quickly into the existing wizard:

<img width="531" alt="screen shot 2018-11-15 at 10 44 32 am" src="https://user-images.githubusercontent.com/9122899/48563957-755b8900-e8c3-11e8-81b7-44801f4462e0.png">

A new "Use custom script" checkbox should put above Hostname and Authenticated SSH Keys. It is off by default and has an info button next to its label (to assist users who may be unfamiliar).

<img width="510" alt="screen shot 2018-11-15 at 10 42 22 am" src="https://user-images.githubusercontent.com/9122899/48563861-47764480-e8c3-11e8-9b43-c687baefaf10.png">

If the user turns it on, the Hostname and Authenticated SSH Keys fields are hidden entirely and replaced with a resizable "Custom Script" text field for the user to copy/paste their script into.

**Comment by andybraren** [comment]
I should also mention that we have a work-in-progress "Advanced" Step 4 for the Create VM wizard that would contain settings for Cloud-Init/Sysprep and other future features.

This idea is still rough so some fields may not be applicable if "Use custom script" is enabled, but here's what that flow might look like:

![cloud-init-advanced-concept](https://user-images.githubusercontent.com/9122899/48565146-d84e1f80-e8c5-11e8-96bb-81de8827bb98.png)

**Comment by suomiy** [comment]
This is great! Moving some logic from the first tab will make it less cluttered and more organized.
