### ISSUE TITLE
Use noop function instead of constants for strings

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui-components#107]
https://github.com/kubevirt/web-ui-components/pull/105#discussion_r234544200

> imho thats not the right way, we should probably just have all strings go though a noop function atm, once we have an i18n interface, we would implement extracting / replacing the strings at that function.
having it as consts across the code means you can't change the language on runtime too.

**Comment by ohadlevy** [comment]
for reference, foreman uses something similar at https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/react_app/common/I18n.js
