### ISSUE TITLE
fix Migrate VM menu item

### ISSUE THREAD

**Issue by suomiy** [kubevirt/web-ui-components#111]
Migrate action should show up when:
- Vmi exist and Migration object doesn't exist. ResourceKebab needs to be modified to allow multiple resources.

Cancel Migration action should show up when:
- Migration object exists (deletes Migration object)

We should also show some status that the VM is migrating

**Comment by mareklibra** [comment]
I have additional issues.
When clicking `Migrate Virtual Machine` action, following is in console log:

```
checkPropTypes.js:19 Warning: Failed prop type: The prop `virtualMachineInstance` is marked as required in `BasicMigrationDialog`, but its value is `undefined`.
    in BasicMigrationDialog
```
```
Warning: Failed prop type: The prop `resources` is marked as required in `WithResources`, but its value is `undefined`.
    in WithResources
```
```
checkPropTypes.js:19 Warning: Failed prop type: Invalid prop `resources` of type `object` supplied to `WithResources`, expected `array`.
```
