### ISSUE TITLE
Simplify project structure and align it with patternfly-react standards

### ISSUE THREAD

**Issue by vojtechszocs** [kubevirt/web-ui-components#2]
- [x] split `dependencies` vs. `devDependencies`, remove deps we don't need, align deps with `patternfly-react` and oVirt UI projects (`ovirt-engine-ui-extensions`, `ovirt-web-ui`)
- [x] simplify webpack (dev/prod) configs and Jest (test) config
- [x] align ESLint rules with patternfly-react standards, try to use `eslint-plugin-patternfly-react`
- [x] simplify project's scripts like `yarn build` etc. (use CLI where appropriate)
- [x] ensure recent versions of deps, i.e. `yarn outdated`
- [x] document common project conventions in Storybook, using [Foreman](https://theforeman.github.io/foreman/) as the reference
- [ ] document developer workflow and other important stuff in README

**Comment by mareklibra** [comment]
> simplify webpack (dev/prod) configs and Jest (test) config

Makes sense but carefully - let's not deviate from create-react-app more than really required. IMO, it's better to keep "a few more useless" things than breaking the structure much. This approach might help us in the future when upgrading.

**Comment by mareklibra** [comment]
> ensure recent versions of deps, i.e. yarn outdated

And establish a rule to run it at every beginning of new sprint

**Comment by vojtechszocs** [comment]
> Makes sense but carefully - let's not deviate from create-react-app more than really required.

CRA adds lots of unnecessary complexity, both in terms of project's dependencies and its scripts & configuration, in my opinion. I'd like to use webpack v4 (latest stable) and minimize the config to the necessary minimum.

**Comment by vojtechszocs** [comment]
All checklist items except for developer docs are already done.
