### ISSUE TITLE
set bootOrder in CreateVmDialog

### ISSUE THREAD

**Issue by suomiy** [kubevirt/web-ui-components#230]
set explicit bootOrder for all devices when creating VMs. The order of devices designates the boot order. This boot order can be then changed in VmDialog

**Comment by lizsurette** [comment]
I thought we decided to keep this out of the create flow for now and to simply rely on a smart default (also based on Provision Source selected). Then of course allow the user to change it from the details view as you've referred to #199 .

Thoughts @jelkosz?

**Comment by suomiy** [comment]
Sorry for the misunderstanding. Yes you are right. This issue is just from code's perspective.
Implicit behaviour is no bootOrder for other devices. So we have to set it explicitly (automatically by the code)  when creating the VM.

**Comment by lizsurette** [comment]
@suomiy Ah, totally understood :) Sorry for the confusion and thanks for clarifying!
