### ISSUE TITLE
Use tooltip for VM status message

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui-components#254]
We are using link title attribute to show VM status message but we should switch to tooltip

@matthewcarleton
> Do you mean just using title="text" on the link? If so, we should really explore a different approach. The title attribute is not typically exposed in an accessible manner so it wouldn't be available to all users. I would think that a tooltip where a user could click to get further info would be most useful here.

**Comment by suomiy** [comment]
long urls should be tested to check that they are rendered properly

**Comment by matthewcarleton** [comment]
@suomiy I agree. We should get this filed as a bug on the Patternfly React side too.

**Comment by suomiy** [comment]
Looking at this a second time; this should be solvable by using a div container with `overflow-wrap: break-word`, so I guess creating an issue should not be necessary unless we want this to be the default behaviour. 

I think we should also convert to use PF4 tooltips everywhere when fixing this issue.
