### ISSUE TITLE
ClusterOverview - Implement fallback logic when prometheus is not available

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui-components#276]
@lizsurette

Any idea what to show when prometheus is not available ? 

Basically two cases can happen:
Overview card requires prometheus only for some information
ie Details tab - openshift version is detected via promeheus
![prom_na](https://user-images.githubusercontent.com/2078045/54603766-73f2c680-4a45-11e9-9a46-a4ed639c1484.png)
should we not show the field at all or show something like `prometheus not available` as field value?

Second case would be that all informations are detected via prometheus - Cluster Capacity
![prom_na2](https://user-images.githubusercontent.com/2078045/54603881-bfa57000-4a45-11e9-9ff0-e61c97932956.png)

should we hide the card or keep it visible and again show something like `prometheus not available` ?

**Comment by lizsurette** [comment]
> Any idea what to show when prometheus is not available ?

How about an informational icon with "Data Not Available" as an initial implementation?

Here is a very basic suggestion from PatternFly 3 cards view:
https://www.patternfly.org/pattern-library/cards/base-card/#design

And how oVirt is making use of something similar in their Dashboard when a VM is suspended:
https://github.com/lizsurette/ovirt-design/blob/aa17c7ba2b46a3cb1440f86337992404680072e4/user-portal/img/vm-details-suspended.png

Any thoughts @andybraren?

**Comment by andybraren** [comment]
In the future when longer Details cards are implemented (see examples below) I'd worry that including the icon could make it harder to see other (more important) icons. I'd suggest just "Not available" text without an icon, mocked up below.

To prevent the Capacity card from jumping around too much, I think all parts of the card should stay visible but we replace the values with "Not available" or "Unknown". Thoughts on this @lizsurette @mceledonia?

![concept-no-prometheus](https://user-images.githubusercontent.com/9122899/54645546-bbdc1280-4a72-11e9-88e8-389927fb0cd1.png)

![details-longer](https://user-images.githubusercontent.com/9122899/54629967-267b5700-4a4f-11e9-9705-e8b29d157c73.png)

**Comment by lizsurette** [comment]
> In the future when longer Details cards are implemented (see examples below) I'd worry that including the icon could make it harder to see other (more important) icons. I'd suggest just "Not available" text without an icon, mocked up below.
> 
> To prevent the Capacity card from jumping around too much, I think all parts of the card should stay visible but we replace the values with "Not available" or "Unknown". Thoughts on this @lizsurette @mceledonia?

I'm happy with both of these suggestions :) @mceledonia - what do you think?

**Comment by mceledonia** [comment]
I think they're both good solutions but I would lean towards Andy's suggestion of using the just text, and avoiding it jumping around.
