### ISSUE TITLE
add attach PVC without clone functionality + refactor naming

### ISSUE THREAD

**Issue by suomiy** [kubevirt/web-ui-components#283]
moving the conversation from https://github.com/kubevirt/web-ui-components/pull/241 to here.

The current state:
Attach Disk -> clones and attaches PVC
Provision source IMAGE -> clones and boots from PVC

The new flow of storage tab should take this into account and add a possibility to attach PVC without cloning and to unify the naming across the whole UI.

**Comment by suomiy** [comment]
@aglitke @matthewcarleton

**Comment by matthewcarleton** [comment]
Do we need both the concept of attach and clone or can we just stick with clone? If so I think what we have proposed for the storage step makes sense (`add` versus `create` and `attach`). Is there a benefit to attaching without cloning?

**Comment by suomiy** [comment]
> Do we need both the concept of attach and clone or can we just stick with clone? 

cc @jelkosz 

> If so I think what we have proposed for the storage step makes sense (add versus create and attach).

I agree; to click add and then choose the specifics. There could be also an option/checkbox for cloning.

> Is there a benefit to attaching without cloning?

There is. Users can create/import their own PVCs and wish to use it only in their one VM. Forcing cloning leads to wasting storage space.

**Comment by matthewcarleton** [comment]
>There is. Users can create/import their own PVCs and wish to use it only in their one VM. Forcing cloning leads to wasting storage space.

so it seems like we will want to offer both clone and attach. We could go with @aglitke suggestion of `clone disk` and `attach disk`. In storage when selecting we can add an `clone this disk` checkbox. Does that make sense?

**Comment by suomiy** [comment]
it does if I understand it correctly. So we would add `CLONE_DISK` as a provisioning source now and then fix/implement the storage tab in the future.

**Comment by matthewcarleton** [comment]
yes, I believe so. I'd like @aglitke thoughts on this too, but that makes sense to me.

**Comment by suomiy** [comment]
changed to `Cloned Disk` in #291
