### ISSUE TITLE
Mockups for not available/loading state in dashboard cards

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui-components#310]
@andybraren can you please provide us designs for not available/loading states for all cards ? similar to https://github.com/kubevirt/web-ui-components/issues/286

**Comment by andybraren** [comment]
Acknowledged - will do soon.

**Comment by andybraren** [comment]
Following up on this old issue - all of our new "Round 2" card designs include loading and unavailable states, and we’ll be sure to design them for any new cards in the future.

PatternFly 4 doesn’t include a skeleton loader pattern ([yet](https://github.com/patternfly/patternfly-design/issues/726)), but [this React component](https://cloud.redhat.com/docs/storybook?path=//story/components--skeleton) from the Insights Storybook is basically what we’d like to use anywhere that we’d previously use a spinner.
