### ISSUE TITLE
Inventory card: Remove all green "okay" statuses and make rows clickable

### ISSUE THREAD

**Issue by andybraren** [kubevirt/web-ui-components#359]
Removing all green "okay" statuses in the Inventory card should make it significantly easier to see more important error/warning/progress statuses and reduce the amount of green on the dashboard even when things aren't fully healthy.

Clicking a row should bring the user to that resource's List page. Clicking a row's status icon/number (if one exists) should bring the user to the same resource's List page, but with a filter applied to only show items with that status (if a filter is available, otherwise just an unfiltered view).

`cursor: pointer;` should apply on hover to change the mouse cursor. `background-color` should be set to PatternFly 4's `pf-black-150`.

Let us know if there are any questions/concerns/gaps about this that you'd like us to clarify!

![0d-inventory](https://user-images.githubusercontent.com/9122899/56147876-1df73d00-5f77-11e9-85fe-6f5c1b849028.png)

**Comment by jelkosz** [comment]
> but with a filter applied to only show items with that status (if a filter is available, otherwise just an unfiltered view).

this is currently not possible, to make it possible will require a significant amount of work. Just to set expectations :)

**Comment by andybraren** [comment]
@jelkosz My expectations have been adjusted. 😄

I noticed that clicking filters in table views adds URL parameters like:

    /pods?rowFilter-pod-status=Failed
    /pods?rowFilter-pod-status=Pending

But if figuring out what those parameters are so that we can link to them from the Inventory card isn't possible, that's fine for now. 🙂

**Comment by jelkosz** [comment]
> But if figuring out what those parameters are so that we can link to them from the Inventory card isn't possible, that's fine for now. slightly_smiling_face

maybe I was not exact enough :) Some of the filters are possible (the ones you found) and some are not (for example VM migrating). So we could implement the clickable rows but the filter would not be correct all the time.

**Comment by andybraren** [comment]
Sometimes correct sounds good to me (better than never correct). 👍
